### ISSUE TITLE
bro does not start

### ISSUE THREAD

**Issue by oflebbe** [danielguerra69/bro-debian-elasticsearch#7]
In bro-extra
@load policy/protocols/conn/mac-logging

the file is not available in the container

**Comment by danielguerra69** [comment]
Sorry it has been removed by the bro team.
The develop tag in hub.docker has all source.
There are major problems with bro and elasticsearch.
But also other things since the 2.5 release. I’m working
on an improvements. Try my new alpine-bro.

https://hub.docker.com/r/danielguerra/alpine-bro/ https://hub.docker.com/r/danielguerra/alpine-bro/

**Comment by danielguerra69** [comment]
Bro is compiling again , they have seen the light and orphaned the elastic plugin instead of depricated. I have to check its all doing well

**Comment by danielguerra69** [comment]
The latest version is building. It should work. In my test its working.

**Comment by danielguerra69** [comment]
hub.docker is crunching on the new image.
It should work now. I have added mac-logging
and app-stats to bro-extra. I will close it when you
confirm all is working again.

**Comment by danielguerra69** [comment]
The image is working again

**Comment by oflebbe** [comment]
Thanks! I can remove my workarounds now!
